### PR TITLE
Update dependencies

### LINKED ISSUE #69: Update unsecure dependency
One of `tumblr.js`'s dependencies, [`request`](https://github.com/tumblr/tumblr.js/blob/master/package.json#L42), contains a child dependency with a security vulnerability (`hoek`). As of 5 days ago, a new version of `request` was published without this vulnerability ([see comment here](https://github.com/request/request/pull/2943#issuecomment-390577329)).

Could you please bump the required version of `request` to `^2.87.0`?

Thanks!

### PR DESCRIPTION
**Pull request by bjornstar**
* To avoid complaints from `npm audit` I updated all the dependencies (fixes #69)
* Replaced gulp with simple npm scripts: lint & mocha
* Updated the tested node versions to the three modern versions: 6, 8 & 10
* Updated the README to document the change from gulp to npm scripts
* Replaced istanbul with nyc (it's the same project)
* Updated the minimum node version to 6
* Regenerated docs (there was an issue with one of the links so I tweaked it to match the other links)
* Removed unused, deprecated eslint option: ecmaFeatures

### CODE REVIEW

**Comment by bjornstar** [comment]
Any interest in moving forward with this?

**Comment by oliverjessner** [comment]
Sadly it looks like the tumblr team is not very active :(

**Comment by ceyko** [comment]
Hey @bjornstar this looks great, thanks!

Only thing we need from you now to merge this is to accept our CLA. I don't see one currently on file for your github user, so can you please visit https://yahoocla.herokuapp.com/ and agree to the terms? Thanks! :)

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Pull request merged**
