### PR TITLE
Loose request version

### PR DESCRIPTION
**Pull request by roderickhsiao**
Will be good to loose the dependency so that customer don't need to download multiple version of the same package and reduce the overall app package size. (`request` itself is quite large)

Major package version with breaking change should be manually update.

### CODE REVIEW

**Comment by roderickhsiao** [comment]
@irace @maddalab how do yo think?

**Comment by irace** [comment]
I'll defer to @ceykooo and team on this (I haven’t worked on tumblr.js in years)

**Comment by ceykooo** [comment]
Sounds good. Tested with latest `request@2.58.0` to confirm and :+1:

**Comment by roderickhsiao** [comment]
Thanks! 
would be good if we can have a patch version update for this change? @ceykooo

**Comment by roderickhsiao** [comment]
@KevinTCoughlin and team, do you think we can have have any patch release in the near future?

**Comment by nicolashenry** [comment]
+1 for a patch release

**Comment by ceyko** [comment]
@roderickhsiao @nicolashenry Done. `v0.0.7` should have it.

**Comment by roderickhsiao** [comment]
Thanks a lot :)

**Pull request merged**
